// Generated by gtest/interal/hack/gen.go

package gtest

import (
  "github.com/smartystreets/assertions"
)

var (
  ShouldAlmostEqual = assertions.ShouldAlmostEqual
  ShouldBeBetween = assertions.ShouldBeBetween
  ShouldBeBetweenOrEqual = assertions.ShouldBeBetweenOrEqual
  ShouldBeBlank = assertions.ShouldBeBlank
  ShouldBeChronological = assertions.ShouldBeChronological
  ShouldBeEmpty = assertions.ShouldBeEmpty
  ShouldBeFalse = assertions.ShouldBeFalse
  ShouldBeGreaterThan = assertions.ShouldBeGreaterThan
  ShouldBeGreaterThanOrEqualTo = assertions.ShouldBeGreaterThanOrEqualTo
  ShouldBeIn = assertions.ShouldBeIn
  ShouldBeLessThan = assertions.ShouldBeLessThan
  ShouldBeLessThanOrEqualTo = assertions.ShouldBeLessThanOrEqualTo
  ShouldBeNil = assertions.ShouldBeNil
  ShouldBeTrue = assertions.ShouldBeTrue
  ShouldBeZeroValue = assertions.ShouldBeZeroValue
  ShouldContain = assertions.ShouldContain
  ShouldContainSubstring = assertions.ShouldContainSubstring
  ShouldEndWith = assertions.ShouldEndWith
  ShouldEqual = assertions.ShouldEqual
  ShouldHappenAfter = assertions.ShouldHappenAfter
  ShouldHappenBefore = assertions.ShouldHappenBefore
  ShouldHappenBetween = assertions.ShouldHappenBetween
  ShouldHappenOnOrAfter = assertions.ShouldHappenOnOrAfter
  ShouldHappenOnOrBefore = assertions.ShouldHappenOnOrBefore
  ShouldHappenOnOrBetween = assertions.ShouldHappenOnOrBetween
  ShouldHappenWithin = assertions.ShouldHappenWithin
  ShouldHaveSameTypeAs = assertions.ShouldHaveSameTypeAs
  ShouldImplement = assertions.ShouldImplement
  ShouldNotAlmostEqual = assertions.ShouldNotAlmostEqual
  ShouldNotBeBetween = assertions.ShouldNotBeBetween
  ShouldNotBeBetweenOrEqual = assertions.ShouldNotBeBetweenOrEqual
  ShouldNotBeBlank = assertions.ShouldNotBeBlank
  ShouldNotBeEmpty = assertions.ShouldNotBeEmpty
  ShouldNotBeIn = assertions.ShouldNotBeIn
  ShouldNotBeNil = assertions.ShouldNotBeNil
  ShouldNotContain = assertions.ShouldNotContain
  ShouldNotContainSubstring = assertions.ShouldNotContainSubstring
  ShouldNotEndWith = assertions.ShouldNotEndWith
  ShouldNotEqual = assertions.ShouldNotEqual
  ShouldNotHappenOnOrBetween = assertions.ShouldNotHappenOnOrBetween
  ShouldNotHappenWithin = assertions.ShouldNotHappenWithin
  ShouldNotHaveSameTypeAs = assertions.ShouldNotHaveSameTypeAs
  ShouldNotImplement = assertions.ShouldNotImplement
  ShouldNotPanic = assertions.ShouldNotPanic
  ShouldNotPanicWith = assertions.ShouldNotPanicWith
  ShouldNotPointTo = assertions.ShouldNotPointTo
  ShouldNotResemble = assertions.ShouldNotResemble
  ShouldNotStartWith = assertions.ShouldNotStartWith
  ShouldPanic = assertions.ShouldPanic
  ShouldPanicWith = assertions.ShouldPanicWith
  ShouldPointTo = assertions.ShouldPointTo
  ShouldResemble = assertions.ShouldResemble
  ShouldStartWith = assertions.ShouldStartWith
)
